---
title: The title of your Semesterproject
subtitle: A subtle subtitle
author: Cyril Geistlich and Micha Franz
output: html
---


<!-- You can add  your R Code with Code chunks-->

```{r}
#| echo: false
#| warning: false
#| message: false

# You can set chunk options individually per code chunk, as was done with this
# code chunk.

# echo: false           hides the code from the generated output
# warning: false        hides warnings from the generated output
# message: false        hides messages from the generated output

# To apply the setting for all code chunks, add the options to the yaml header of the document (in between the ---) without the preceeding "#|".

```


## Abstract


This project aims to investigate key factors and features in GPS tracking data to differentiate transportation vehicles. Machine learning is applied to automate transportation mode detection using spatial, temporal, and attribute analysis. Manual verification of results ensures accuracy. The findings contribute to computational movement analysis and automated transportation mode detection.

## Introduction

## Research Question

What are the key factors and features that can be extracted from GPS tracking data to differentiate between different types of transportation modes?
How can machine learning techniques be applied to GPS tracking data to automate the detection of the mode of transportation and which accuracies can be achieved by different machine learning algorithms?


## Material and Methods

<!-- the following is just a placeholder text, remove it!-->
Christianity revaluation value battle faithful marvelous society derive free truth. Right battle mountains superiority grandeur ascetic grandeur merciful. Derive against intentions burying salvation ocean. Right intentions dead victorious ideal spirit evil ultimate joy. Holiest spirit value oneself contradict aversion christianity ultimate convictions war christian.

## Results

<!-- the following is just a placeholder text, remove it!-->
Philosophy oneself passion play fearful self noble zarathustra deceptions sexuality. Endless ocean of oneself dead ocean. Selfish decrepit.

## Discussion

<!-- the following is just a placeholder text, remove it!-->
Justice convictions spirit sexuality insofar free marvelous joy. Revaluation virtues mountains spirit fearful sexuality love endless. Society intentions will noble burying aversion moral. Insofar passion ultimate mountains of play gains depths joy christian reason christianity mountains dead. Mountains christianity play war holiest ascetic passion oneself derive grandeur. Against pinnacle hope joy burying ocean of horror disgust victorious faithful justice suicide.


## Code

# 1. Data Prep
## 1.1 Read Data
## 1.2 Clean Data (if necessary)
## 1.3 Calculate Movement Parameters
### 1.3.1 Speed
### 1.3.2 Acceleration
### 1.3.3 Sinuosity
### 1.3.4 Closeness to Traffic Network
### 1.3.5 Water Bodies (For boats)
### 1.3.6 Slope?
### 

# 2.PCA


# 3. Categories
Walk (Running?)
Bike
Train
Tram
Bus
Car
Skateboard
Scooter
Boat
Other
